spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JsonDiff?useSSL=false&serverTimezone=UTC
    username: root
    password: lxy200222
    driver-class-name: com.mysql.cj.jdbc.Driver

# MP 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
